### ISSUE TITLE
更新了

### ISSUE THREAD

**Issue by LeiHao0** [candyan/AlipaySDK#1]
Hi, 这个是官方的还是？

现在 2.1.2 了

**Comment by candyan** [comment]
@Artwalk 是从官方要的sdk。一直没有找到哪里有最新且稳定的SDK下载入口 %>_<%

**Comment by neufeng** [comment]
http://doc.open.alipay.com/doc2/detail?treeId=59&articleId=103563&docType=1

**Comment by neufeng** [comment]
又更新了，支持bitcode

**Comment by candyan** [comment]
@neufeng 3.0.1 吗?

**Comment by neufeng** [comment]
@candyan 是的版本号没变，更新日期是2015-10-13

**Comment by candyan** [comment]
@neufeng  版本号没变。。。。。。=_=|| 行吧

**Comment by candyan** [comment]
@neufeng 3.0.1.2 已经上传到 pod 上了
